### ISSUE TITLE
safebox via npm constantly fails 

### ISSUE THREAD

**Issue by adikari** [monebag/safebox#15]
```


➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDOUT downloading safebox binary
--
15:14:08.384 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR
15:14:08.384 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR gzip: stdin: unexpected end of file
15:14:08.384 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR tar: Unexpected EOF in archive
15:14:08.385 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR tar: Unexpected EOF in archive
15:14:08.385 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR tar: Error is not recoverable: exiting now
15:14:08.388 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR node:child_process:946
15:14:08.389 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     throw err;
15:14:08.389 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     ^
15:14:08.389 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR
15:14:08.389 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR Error: Command failed: tar -xf /tmp/safebox.tar.gz -C /tmp
15:14:08.389 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR
15:14:08.389 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR gzip: stdin: unexpected end of file
15:14:08.390 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR tar: Unexpected EOF in archive
15:14:08.390 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR tar: Unexpected EOF in archive
15:14:08.390 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR tar: Error is not recoverable: exiting now
15:14:08.391 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR
15:14:08.391 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     at checkExecSyncError (node:child_process:871:11)
15:14:08.391 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     at Object.execSync (node:child_process:943:15)
15:14:08.391 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     at Request.<anonymous> (/vercel/path0/node_modules/@adikari/safebox/install.js:44:8)
15:14:08.391 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     at Request.emit (node:events:513:28)
15:14:08.391 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     at Request.<anonymous> (/vercel/path0/node_modules/request/request.js:1091:14)
15:14:08.391 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     at Request.emit (node:events:525:35)
15:14:08.391 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     at IncomingMessage.<anonymous> (/vercel/path0/node_modules/request/request.js:1076:12)
15:14:08.391 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     at Object.onceWrapper (node:events:627:28)
15:14:08.391 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     at IncomingMessage.emit (node:events:525:35) {
15:14:08.392 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR   status: 2,
15:14:08.392 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR   signal: null,
15:14:08.392 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR   output: [
15:14:08.392 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     null,
15:14:08.392 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     Buffer(0) [Uint8Array] [],
15:14:08.392 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     Buffer(142) [Uint8Array] [
15:14:08.392 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR        10, 103, 122, 105, 112,  58,  32, 115, 116, 100, 105, 110,
15:14:08.392 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR        58,  32, 117, 110, 101, 120, 112, 101,  99, 116, 101, 100,
15:14:08.392 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR        32, 101, 110, 100,  32, 111, 102,  32, 102, 105, 108, 101,
15:14:08.392 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR        10, 116,  97, 114,  58,  32,  85, 110, 101, 120, 112, 101,
15:14:08.392 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR        99, 116, 101, 100,  32,  69,  79,  70,  32, 105, 110,  32,
15:14:08.392 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR        97, 114,  99, 104, 105, 118, 101,  10, 116,  97, 114,  58,
15:14:08.393 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR        32,  85, 110, 101, 120, 112, 101,  99, 116, 101, 100,  32,
15:14:08.393 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR        69,  79,  70,  32, 105, 110,  32,  97, 114,  99, 104, 105,
15:14:08.393 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR       118, 101,  10, 116,
15:14:08.393 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR       ... 42 more items
15:14:08.393 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     ]
15:14:08.393 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR   ],
15:14:08.393 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR   pid: 391,
15:14:08.393 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR   stdout: Buffer(0) [Uint8Array] [],
15:14:08.393 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR   stderr: Buffer(142) [Uint8Array] [
15:14:08.393 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR      10, 103, 122, 105, 112,  58,  32, 115, 116, 100, 105, 110,
15:14:08.394 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR      58,  32, 117, 110, 101, 120, 112, 101,  99, 116, 101, 100,
15:14:08.394 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR      32, 101, 110, 100,  32, 111, 102,  32, 102, 105, 108, 101,
15:14:08.394 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR      10, 116,  97, 114,  58,  32,  85, 110, 101, 120, 112, 101,
15:14:08.394 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR      99, 116, 101, 100,  32,  69,  79,  70,  32, 105, 110,  32,
15:14:08.394 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR      97, 114,  99, 104, 105, 118, 101,  10, 116,  97, 114,  58,
15:14:08.394 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR      32,  85, 110, 101, 120, 112, 101,  99, 116, 101, 100,  32,
15:14:08.394 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR      69,  79,  70,  32, 105, 110,  32,  97, 114,  99, 104, 105,
15:14:08.394 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     118, 101,  10, 116,
15:14:08.394 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR     ... 42 more items
15:14:08.394 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR   ]
15:14:08.394 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR }
15:14:08.394 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR
15:14:08.395 | ➤ YN0000: │ @adikari/safebox@npm:1.2.0 STDERR Node.js v18.12.1
15:14:08.396 | ➤ YN0009: │ @adikari/safebox@npm:1.2.0 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-ea208742/build.log)

```

**Comment by adikari** [comment]
this is most likely because the download of binary did not work correctly
